apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- rollout.yaml
namespace: staging
commonAnnotations:
  supported-by: sre@example.com
spec:
  containers:
  - image: schoolofdevops/vote:v4
  name: vote
labels:
- includeSelectors: false
  pairs:
    project: instavote
patches:
- path: service.yaml
